sudo: required

language: perl6

perl6:
    - latest

env:
    PATH=$PATH:$HOME/silan/bin

install:
    - rakudobrew build-panda
    - panda installdeps .
    # install silan binary so that Audio::Silan can be tested
    - mkdir -p $HOME/silan
    - sudo apt-get install libsndfile-dev
    - wget https://github.com/x42/silan/archive/v0.3.2.tar.gz
    - tar -xvzf v0.3.2.tar.gz
    - cd silan-0.3.2 && autoreconf --install && ./configure --prefix=$HOME/silan && make && make install && cd ..
